# this_file: .github/dependabot.yml
version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      development-dependencies:
        patterns:
          - "black"
          - "mypy"
          - "pytest*"
          - "ruff"
          - "twine"
  
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"